default_platform :ios

ROOT_DIR = File.dirname(Dir.pwd)

BASE_IDENTIFIER = "com.keita.oouchi.minQ"

IDENTIFIERS = [
  "#{BASE_IDENTIFIER}",
  "#{BASE_IDENTIFIER}.dev",
].join(",")
ExportOption = Struct.new(:identifier, :configuration, :export_method)

platform :ios do

  desc "セットアップ(Certifications, CocoaPods, Carthage)"
  lane :setup do |options|
    cocoapods(try_repo_update_on_error: true)
  end

  desc "Releaseビルドを作成してAppStoreにアップロードする"
  lane :submit do
    UI.header("Releaseアップロード開始")
    ensure_git_status_clean
    match(app_identifier: "com.keita.oouchi.minQ", type: "appstore")

    gym(
      workspace: "MINQ.xcworkspace",
      scheme: "MINQ-Release",
      clean: true,
      silent: true,
      export_method: "app-store",
      include_symbols: true,
      include_bitcode: true,
      configuration: "Release",
      output_name: "MINQ.Release",
      output_directory: File.join(ROOT_DIR, "build")
    )

    appstore(
      app_identifier: BASE_IDENTIFIER,
      skip_binary_upload: false,
      skip_screenshots: true
    )
  end

  desc "Certificates"
  lane :certificates do |options|
    match(app_identifier: "com.keita.oouchi.minQ.dev", type: "development")
    match(app_identifier: "com.keita.oouchi.minQ.dev", type: "adhoc")
    match(app_identifier: "com.keita.oouchi.minQ", type: "appstore")
  end

  desc "ストア用スクショ作成"
  lane :screenshots do
    frameit(path: './fastlane/screenshots')
  end
end